export const EVAL_STATUS = {
  SUCCESS: "EVAL_STATUS.SUCCESS",
  ERROR: "EVAL_STATUS.ERROR",
  WRONG_EXPRESSION: "EVAL_WRONG_EXPRESSION",
};

export const TRANSACTION_MODE = {
  INCOME: "TRANSACTION_MODE.INCOME",
  EXPENSE: "TRANSACTION_MODE.EXPENSE",
};
